<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.zzb</groupId>
        <artifactId>quick</artifactId>
        <version>3.0.0</version>
    </parent>

    <artifactId>quick-plugin</artifactId>
    <packaging>pom</packaging>
    <description>插件模块</description>

    <modules>
        <!-- 登录鉴权插件 -->
        <module>quick-plugin-auth</module>

        <!-- 业务功能插件 -->
        <module>quick-plugin-biz</module>

        <!-- 事故业务功能插件 -->
        <module>quick-plugin-sg</module>

         <!-- C端功能插件 -->
        <module>quick-plugin-client</module>

        <!-- 开发工具插件 -->
        <module>quick-plugin-dev</module>

        <!-- 代码生成插件 -->
        <module>quick-plugin-gen</module>

        <!-- 移动端管理插件 -->
        <module>quick-plugin-mobile</module>

        <!-- 系统功能插件 -->
        <module>quick-plugin-sys</module>
    </modules>

</project>
